# Generated by Django 4.1.7 on 2023-03-25 12:39

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpage_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='content',
            field=wagtail.fields.StreamField([('html', wagtail.blocks.RawHTMLBlock())], blank=True, null=True, use_json_field=None),
        ),
    ]
